  
version: "3"

services:
  vote:
    build: ./vote-app
    command: python app.py
    volumes:
     - ./vote-app:/app
    ports:
      - "5001:5001"

  redis:
    image: redis:alpine
    ports: ["6379"]
