apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    name: voiting-service
    app: demo-voting-app
spec:
  type: NodePort
  selector:
    name: voting-app-pod
    app: demo-voting-app
  ports:
    - port: 5001
      targetPort: 5001
      nodePort: 30010