spring:
  datasource:
#    driver-class-name: org.postgresql.Driver
    #    url: jdbc:postgres://localhost:5432/votingdb
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  hikari:
    initialization-fail-timeout: 0
  jpa:
    database-platform: org.hibernate.dialect.PostgresPlusDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create
  redis:
    host: ${REDIS_HOST}
    port: 6379