apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  index.html: |
    <h1>What the Helm!!!</h1>
volumeMounts:
      - name: nginx
        mountPath: /usr/share/nginx/html
volumes:
  - name: nginx
    configMap:
      name: nginx-configmap