apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app
spec:
  selector:
    matchLabels:
      app: result-app
  template:
    metadata:
      labels:
        app: result-app
    spec:
      containers:
       - name: result-app
         image: resultapp
         imagePullPolicy: IfNotPresent
         ports:
           - containerPort: 3001

---
apiVersion: v1
kind: Service
metadata:
  name: resultapp-service
  labels:
    name: resultapp-service 
spec:
  type: NodePort
  selector: 
    app: result-app
  ports:
  - port: 3001
    targetPort: 3001
    nodePort: 30005