apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
spec:
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
        - name: vote
          image: voteapp
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5001
          env:
            - name: REDIS_HOST
              value: redis
---
apiVersion: v1
kind: Service
metadata:
  name: votews
spec:
  type: NodePort
  selector:
    app: vote
  ports:
    - port: 5001
      targetPort: 5001
      nodePort: 30012
