apiVersion: apps/v1
kind: Deployment
metadata:
  name: voteui
spec:
  selector:
    matchLabels:
      app: voteui
  template:
    metadata:
      labels:
        app: voteui
    spec:
      containers:
        - name: voteui
          image: voteui
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4200
          # resources:
          #            limits:
          #              memory: "200Mi"
          #            requests:
          #              memory: "100Mi"
          #          command:
          #            - --kubelet-insecure-tls=true
          #            - --kubelet-preferred-address-types=InternalIP
          #            - --cert-dir=/tmp
          #            - --secure-port=4443
          env:
            - name: VOTEAPP_URL
              value: voteapp
            - name: VOTE_HOST
              valueFrom:
                configMapKeyRef:
                  name: vote-conf
                  key: VOTE_HOST
            - name: VOTE_PORT
              valueFrom:
                configMapKeyRef:
                  name: vote-conf
                  key: VOTE_PORT
---
apiVersion: v1
kind: Service
metadata:
  name: voteui
spec:
  type: NodePort
  selector:
    app: voteui
  ports:
    - port: 4200
      targetPort: 4200
      nodePort: 30002
