apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
spec:
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
        - name: result
          image: resultapp:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3001
#          env:
#            - name: DB_HOST
#              valueFrom:
#                configMapKeyRef:
#                  name: vote-conf
#                  key: DB_HOST
#            - name: POSTGRES_DB
#              valueFrom:
#                configMapKeyRef:
#                  name: vote-conf
#                  key: POSTGRES_DB
#            - name: DB_USER
#              valueFrom:
#                configMapKeyRef:
#                  name: vote-conf
#                  key: POSTGRES_USER
#            - name: DB_PASSWORD
#              valueFrom:
#                configMapKeyRef:
#                  name: vote-conf
#                  key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: result
spec:
#  type: NodePort
  selector:
    app: result
  ports:
    - port: 3001
      protocol: TCP
#      targetPort: 3001
#      nodePort: 30005


