
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name}}
  labels:
    {{- include "voteapp.labels" . | nindent 4}}
spec:
  selector:
    {{- include "voteapp.selectorLabels" . | nindent 6}}
  type: {{ .Values.service.type}}
  ports:
    - port: {{ .Values.service.port}}
      targetPort: {{ .Values.service.targetPort}}
      nodePort: {{ .Values.service.nodePort}}
